Glide clearDiskCache() must be run on background thread
STACK_TRACE_HASH=d9392158
java.lang.RuntimeException: Unable to start receiver org.fdroid.fdroid.receiver.DeviceStorageReceiver: java.lang.IllegalArgumentException: You must call this method on a background thread
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3426)
	at android.app.ActivityThread.access$1200(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1667)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.IllegalArgumentException: You must call this method on a background thread
	at com.bumptech.glide.util.Util.assertBackgroundThread(Util.java:173)
	at com.bumptech.glide.Glide.clearDiskCache(Glide.java:730)
	at org.fdroid.fdroid.receiver.DeviceStorageReceiver.onReceive(DeviceStorageReceiver.java:26)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3417)
	... 8 more
java.lang.IllegalArgumentException: You must call this method on a background thread
	at com.bumptech.glide.util.Util.assertBackgroundThread(Util.java:173)
	at com.bumptech.glide.Glide.clearDiskCache(Glide.java:730)
	at org.fdroid.fdroid.receiver.DeviceStorageReceiver.onReceive(DeviceStorageReceiver.java:26)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3417)
	at android.app.ActivityThread.access$1200(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1667)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)