ignore mystery NoClassDefFoundError, etc. crashes in WifiApControl
I looked into this and have no idea how it could be caused, or even how it
is possible for it to happen.  The WifiApControl is only for old Android
releases anyway, so F-Droid should not crash even if this feature does not
work.

#2477
acra-crash-reports#12
acra-crash-reports#31
acra-crash-reports#39