remove Nearby from menu on SDK<26, it is borked
Looks like there would have to be "desugaring" or something like included to
make it work, since `java.nio` was added in SDK 26:

```
java.lang.NoSuchMethodError: No virtual method toPath()Ljava/nio/file/Path; in class Ljava/io/File; or its super classes (declaration of 'java.io.File' appears in /system/framework/core-oj.jar)
    at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:927)
    at org.fdroid.fdroid.nearby.LocalRepoManager.writeIndexJar(LocalRepoManager.java:289)
    at org.fdroid.fdroid.nearby.LocalRepoManager.generateIndex(LocalRepoManager.java:265)
    at org.fdroid.fdroid.nearby.LocalRepoService.runProcess(LocalRepoService.java:107)
    at org.fdroid.fdroid.nearby.LocalRepoService$GenerateLocalRepoThread.run(LocalRepoService.java:96)
```