Android does not support hi-Latn, so remove it
It is breaking the build:

```
Execution failed for task ':app:processBasicDefaultDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR: AAPT: error: invalid config 'hi-rLatn' for -c option.
```

* https://gitlab.com/fdroid/fdroidclient/-/merge_requests/1753#note_3883912852
* https://gitlab.com/fdroid/fdroidclient/-/jobs/16651356618