wait-for-emulator: skip adb log messages
Otherwise, we'd interpret this as "booting", which is wrong:

     $ adb -e shell getprop init.svc.bootanim
    * daemon not running. starting it now on port 5037 *
    * daemon started successfully *
    error: no devices found